# Generated by Django 3.0.2 on 2020-02-14 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('ref', models.CharField(max_length=1024, verbose_name='Reference')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('keywords', models.CharField(max_length=1024, verbose_name='Keywords, phrases')),
                ('inactive', models.BooleanField(verbose_name='Inactive')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='Active Period Start')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='Active Period End')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Site', verbose_name='Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.DateTimeField(blank=True, null=True, verbose_name='News date')),
                ('ref', models.CharField(max_length=1024, verbose_name='Reference')),
                ('brief_info', models.TextField(blank=True, verbose_name='Brief')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Topic', verbose_name='Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
