# Generated by Django 3.0.2 on 2020-02-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='site',
        ),
        migrations.AddField(
            model_name='news',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='site',
            name='descr',
            field=models.CharField(max_length=1024, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(verbose_name='News date'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Topic Name'),
        ),
        migrations.CreateModel(
            name='TopicSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Site', verbose_name='Site')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Topic', verbose_name='Topic')),
            ],
        ),
    ]
