# Generated by Django 3.0.2 on 2020-02-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200224_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='info',
            field=models.TextField(blank=True, verbose_name='News'),
        ),
    ]
