# Generated by Django 3.0.2 on 2020-02-06 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200206_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 12, 25, 27, 981065, tzinfo=utc)),
        ),
    ]
