# Generated by Django 3.0.2 on 2020-02-14 05:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200206_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 5, 17, 10, 79737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Age'),
        ),
    ]
