# Generated by Django 3.0.2 on 2020-02-21 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20200221_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 7, 1, 3, 379474, tzinfo=utc)),
        ),
    ]
